# Database specific configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesdb
    username: root
    password: root

  # JPA specific configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT-CATALOG  

  profiles:
    active: dev  # Set active profile

server:
  port: 5555

# Eureka configuration
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY

# Management & Actuator configuration
management:
  endpoints:
    web:
      base-path: /management-dashboard
      exposure:
        include: "*"
        exclude: beans   

# Custom properties
message: Hello
databaseName: Mysql
