server:
  port: 5555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicestraining
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


